spring:
  application:
    name: camunda-workflow
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: postgres
    password: 98633589
camunda:
  bpm:
    enabled: true
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true
    filter:
      create: All
    authorization:
      enabled: true
    history-level: full
    auto-deployment-enabled: true
    default-number-of-retries: 3
    job-execution:
      enabled: true
